version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: 'postgres'
            host: 'localhost'
            port: 5432
            database: 'poundy'
            schema: 'public'
            user: 'postgres'
            password: ''
            migrations: false
            ssl: false